ALTER TABLE SEDES.LANDEN ALTER COLUMN BESTAAT TYPE CHAR(1);
ALTER TABLE SEDES.LANDNAMEN RENAME COLUMN LANDNAAM TO NAAM;
ALTER TABLE SEDES.MUNTEN ALTER COLUMN BESTAAT TYPE CHAR(1);
ALTER TABLE SEDES.MUNTEN RENAME COLUMN MUNT TO NAAM;
ALTER TABLE SEDES.REGIOS RENAME COLUMN REGIO TO NAAM;
ALTER TABLE SEDES.WERELDDEELNAMEN RENAME COLUMN WERELDDEELNAAM TO NAAM;

ALTER TABLE SEDES.ADRESSEN ALTER COLUMN ADRES_ID DROP DEFAULT;
ALTER TABLE SEDES.ADRESSEN ALTER COLUMN ADRES_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.adressen', 'adres_id'), COALESCE(MAX(ADRES_ID), 1))
FROM SEDES.ADRESSEN;
DROP SEQUENCE SEDES.SEQ_ADRESSEN;

ALTER TABLE SEDES.KONTAKTADRESSEN ALTER COLUMN KONTAKTADRES_ID DROP DEFAULT;
ALTER TABLE SEDES.KONTAKTADRESSEN ALTER COLUMN KONTAKTADRES_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.kontaktadressen', 'kontaktadres_id'), COALESCE(MAX(KONTAKTADRES_ID), 1))
FROM SEDES.KONTAKTADRESSEN;
DROP SEQUENCE SEDES.SEQ_KONTAKTADRESSEN;

ALTER TABLE SEDES.KONTAKTEN ALTER COLUMN KONTAKT_ID DROP DEFAULT;
ALTER TABLE SEDES.KONTAKTEN ALTER COLUMN KONTAKT_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.kontakten', 'kontakt_id'), COALESCE(MAX(KONTAKT_ID), 1))
FROM SEDES.KONTAKTEN;
DROP SEQUENCE SEDES.SEQ_KONTAKTEN;

ALTER TABLE SEDES.LANDEN ALTER COLUMN LAND_ID DROP DEFAULT;
ALTER TABLE SEDES.LANDEN ALTER COLUMN LAND_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.landen', 'land_id'), COALESCE(MAX(LAND_ID), 1))
FROM SEDES.LANDEN;
DROP SEQUENCE SEDES.SEQ_LANDEN;

ALTER TABLE SEDES.MUNTEN ALTER COLUMN MUNT_ID DROP DEFAULT;
ALTER TABLE SEDES.MUNTEN ALTER COLUMN MUNT_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.munten', 'munt_id'), COALESCE(MAX(MUNT_ID), 1))
FROM SEDES.MUNTEN;
DROP SEQUENCE SEDES.SEQ_MUNTEN;

ALTER TABLE SEDES.PLAATSEN ALTER COLUMN PLAATS_ID DROP DEFAULT;
ALTER TABLE SEDES.PLAATSEN ALTER COLUMN PLAATS_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.plaatsen', 'plaats_id'), COALESCE(MAX(PLAATS_ID), 1))
FROM SEDES.PLAATSEN;
DROP SEQUENCE SEDES.SEQ_PLAATSEN;

ALTER TABLE SEDES.POSTLIJSTEN ALTER COLUMN POSTLIJST_ID DROP DEFAULT;
ALTER TABLE SEDES.POSTLIJSTEN ALTER COLUMN POSTLIJST_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.postlijsten', 'postlijst_id'), COALESCE(MAX(POSTLIJST_ID), 1))
FROM SEDES.POSTLIJSTEN;
DROP SEQUENCE SEDES.SEQ_POSTLIJSTEN;

ALTER TABLE SEDES.REGIOS ALTER COLUMN REGIO_ID DROP DEFAULT;
ALTER TABLE SEDES.REGIOS ALTER COLUMN REGIO_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.regios', 'regio_id'), COALESCE(MAX(REGIO_ID), 1))
FROM SEDES.REGIOS;
DROP SEQUENCE SEDES.SEQ_REGIOS;

ALTER TABLE SEDES.WERELDDELEN ALTER COLUMN WERELDDEEL_ID DROP DEFAULT;
ALTER TABLE SEDES.WERELDDELEN ALTER COLUMN WERELDDEEL_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.werelddelen', 'werelddeel_id'), COALESCE(MAX(WERELDDEEL_ID), 1))
FROM SEDES.WERELDDELEN;
DROP SEQUENCE SEDES.SEQ_WERELDDELEN;

ALTER TABLE SEDES.KONTAKTADRESSEN
  DROP CONSTRAINT FK_KAD_ADRES_ID;

ALTER TABLE SEDES.KONTAKTADRESSEN
  ADD CONSTRAINT FK_KAD_ADRES_ID FOREIGN KEY (ADRES_ID)
  REFERENCES SEDES.ADRESSEN (ADRES_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.KONTAKTADRESSEN
  DROP CONSTRAINT FK_KAD_KONTAKT_ID;

ALTER TABLE SEDES.KONTAKTADRESSEN
  ADD CONSTRAINT FK_KAD_KONTAKT_ID FOREIGN KEY (KONTAKT_ID)
  REFERENCES SEDES.KONTAKTEN (KONTAKT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.LANDEN
  DROP CONSTRAINT FK_LND_MUNT_ID;

ALTER TABLE SEDES.LANDEN
  ADD CONSTRAINT FK_LND_MUNT_ID FOREIGN KEY (MUNT_ID)
  REFERENCES SEDES.MUNTEN (MUNT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.LANDEN
  DROP CONSTRAINT FK_LND_WERELDDEEL_ID;

ALTER TABLE SEDES.LANDEN
  ADD CONSTRAINT FK_LND_WERELDDEEL_ID FOREIGN KEY (WERELDDEEL_ID)
  REFERENCES SEDES.WERELDDELEN (WERELDDEEL_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.PLAATSEN
  DROP CONSTRAINT FK_PLA_LAND_ID;

ALTER TABLE SEDES.PLAATSEN
  ADD CONSTRAINT FK_PLA_LAND_ID FOREIGN KEY (LAND_ID)
  REFERENCES SEDES.LANDEN (LAND_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.PLAATSEN
  DROP CONSTRAINT FK_PLA_REGIO_ID;

ALTER TABLE SEDES.PLAATSEN
  ADD CONSTRAINT FK_PLA_REGIO_ID FOREIGN KEY (REGIO_ID)
  REFERENCES SEDES.REGIOS (REGIO_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.POSTLIJST_KONTAKTEN
  DROP CONSTRAINT FK_PLK_KONTAKT_ID;

ALTER TABLE SEDES.POSTLIJST_KONTAKTEN
  ADD CONSTRAINT FK_PLK_KONTAKT_ID FOREIGN KEY (KONTAKT_ID)
  REFERENCES SEDES.KONTAKTEN (KONTAKT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.POSTLIJST_KONTAKTEN
  DROP CONSTRAINT FK_PLK_POSTLIJST_ID;

ALTER TABLE SEDES.POSTLIJST_KONTAKTEN
  ADD CONSTRAINT FK_PLK_POSTLIJST_ID FOREIGN KEY (POSTLIJST_ID)
  REFERENCES SEDES.POSTLIJSTEN (POSTLIJST_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.REGIOS
  DROP CONSTRAINT FK_REG_LAND_ID;

ALTER TABLE SEDES.REGIOS
  ADD CONSTRAINT FK_REG_LAND_ID FOREIGN KEY (LAND_ID)
  REFERENCES SEDES.LANDEN (LAND_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

COMMIT;
