-- Kreatie van alle objecten voor het Sedes schema.
--
-- Copyright 2012 Marco de Booij
--
-- Licensed under the EUPL, Version 1.1 or - as soon they will be approved by
-- the European Commission - subsequent versions of the EUPL (the "Licence");
-- you may not use this work except in compliance with the Licence. You may
-- obtain a copy of the Licence at:
--
-- http://www.osor.eu/eupl
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the Licence is distributed on an "AS IS" BASIS, WITHOUT
-- WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the Licence for the specific language governing permissions and
-- limitations under the Licence.
--
-- Project: Sedes
-- Author: Marco de Booij

\echo    Passwords
\prompt 'SEDES_APP: ' sedes_app_pw
\set q_sedes_app_pw '\'':sedes_app_pw'\''

-- Gebruikers en rollen.
CREATE ROLE SEDES_APP LOGIN
  PASSWORD :q_sedes_app_pw
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

CREATE SCHEMA SEDES;

CREATE ROLE SEDES_SEL NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
CREATE ROLE SEDES_UPD NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

GRANT USAGE ON SCHEMA SEDES  TO SEDES_SEL;
GRANT USAGE ON SCHEMA SEDES  TO SEDES_UPD;

GRANT SEDES_UPD TO SEDES_APP;

GRANT CONNECT ON DATABASE :DBNAME TO SEDES_APP;

-- Sequences

-- Tabellen
CREATE TABLE SEDES.ADRESSEN (
  ADRES_ID                        INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  ADRESDATA                       VARCHAR(255)    NOT NULL,
  OPMERKING                       VARCHAR(2000),
  PLAATS_ID                       INTEGER,
  SUB_POSTKODE                    VARCHAR(10),
  CONSTRAINT PK_ADRESSEN PRIMARY KEY (ADRES_ID)
);

CREATE TABLE SEDES.KONTAKTADRESSEN (
  ADRES_ID                        INTEGER         NOT NULL,
  EINDDATUM                       DATE,
  KONTAKTADRES_ID                 INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  KONTAKTADRESTYPE                VARCHAR(10)     NOT NULL,
  KONTAKT_ID                      INTEGER         NOT NULL,
  OPMERKING                       VARCHAR(2000),
  STARTDATUM                      DATE            NOT NULL,
  SUB_ADRES                       VARCHAR(255),
  TAAL                            CHAR(3),
  CONSTRAINT PK_KONTAKTADRESSEN PRIMARY KEY (KONTAKTADRES_ID)
);

CREATE TABLE SEDES.KONTAKTEN (
  AANSPREEK_ID                    VARCHAR(10),
  GEBOORTEDATUM                   DATE,
  GEBRUIKERSNAAM                  VARCHAR(20),
  INITIALEN                       VARCHAR(20),
  KONTAKT_ID                      INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  KONTAKTTYPE                     CHAR(1)         NOT NULL  DEFAULT 'P',
  NAAM                            VARCHAR(255)    NOT NULL,
  OPMERKING                       VARCHAR(2000),
  PSEUDONIEM                      VARCHAR(255),
  ROEPNAAM                        VARCHAR(255),
  TAAL                            CHAR(3)         NOT NULL,
  TUSSENVOEGSEL                   VARCHAR(10),
  VOORNAAM                        VARCHAR(255),
  CONSTRAINT PK_KONTAKTEN PRIMARY KEY (KONTAKT_ID)
);

CREATE TABLE SEDES.KONTAKTKONTAKTEN (
  CHILDKONTAKT                    INTEGER         NOT NULL,
  EINDDATUM                       DATE,
  KONTAKTKONTAKT_ID               INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  PARENTKONTAKT                   INTEGER         NOT NULL,
  STARTDATUM                      DATE            NOT NULL,
  CONSTRAINT PK_KONTAKTKONTAKTEN PRIMARY KEY (KONTAKTKONTAKT_ID)
);

CREATE TABLE SEDES.LANDEN (
  BESTAAT                         CHAR(1)         NOT NULL  DEFAULT 'J',
  ISO2                            CHAR(2),
  ISO3                            CHAR(3)         NOT NULL,
  LAND_ID                         INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  LANDNUMMER                      SMALLINT,
  MUNT_ID                         INTEGER         NOT NULL,
  POSTKODE_SCHEIDING              VARCHAR(10),
  POSTKODE_TYPE                   CHAR(1)         NOT NULL  DEFAULT '1',
  POST_LANDKODE                   CHAR(3)         NOT NULL,
  TAAL                            CHAR(2)         NOT NULL,
  VLAG                            BYTEA,
  WERELDDEEL_ID                   INTEGER         NOT NULL,
  CONSTRAINT PK_LANDEN PRIMARY KEY (LAND_ID)
);

CREATE TABLE SEDES.LANDNAMEN (
  HOOFDSTAD                       VARCHAR(100),
  LAND_ID                         INTEGER         NOT NULL,
  NAAM                            VARCHAR(100)    NOT NULL,
  OFFICIELE_NAAM                  VARCHAR(225),
  TAAL                            CHAR(2)         NOT NULL,
  CONSTRAINT PK_LANDNAMEN PRIMARY KEY (LAND_ID, TAAL)
);

CREATE TABLE SEDES.MUNTEN (
  BESTAAT                         CHAR(1)         NOT NULL  DEFAULT 'J',
  DECIMALEN                       SMALLINT        NOT NULL  DEFAULT '2',
  ISO3                            CHAR(3)         NOT NULL,
  MUNT_ID                         INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  MUNTTEKEN                       CHAR(3),
  NAAM                            VARCHAR(100)    NOT NULL,
  SUBEENHEID                      VARCHAR(100),
  CONSTRAINT PK_MUNTEN PRIMARY KEY (MUNT_ID)
);

CREATE TABLE SEDES.PLAATSEN (
  BREEDTE                         CHAR(1),
  BREEDTEGRAAD                    NUMERIC(4,2),
  LAND_ID                         INTEGER         NOT NULL,
  LENGTE                          CHAR(1),
  LENGTEGRAAD                     NUMERIC(5,2),
  PLAATS_ID                       INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  PLAATSNAAM                      VARCHAR(100)    NOT NULL,
  POSTKODE                        VARCHAR(15),
  REGIO_ID                        INTEGER,
  ZONENUMMER                      INTEGER,
  CONSTRAINT PK_PLAATSEN PRIMARY KEY (PLAATS_ID)
);

CREATE TABLE SEDES.POSTLIJST_KONTAKTEN (
  EINDDATUM                       DATE,
  KONTAKT_ID                      INTEGER         NOT NULL,
  POSTLIJST_ID                    INTEGER         NOT NULL,
  STARTDATUM                      DATE            NOT NULL,
  CONSTRAINT PK_POSTLIJST_KONTAKTEN PRIMARY KEY (POSTLIJST_ID, KONTAKT_ID, STARTDATUM)
);

CREATE TABLE SEDES.POSTLIJSTEN (
  POSTLIJST                       VARCHAR(100)    NOT NULL,
  POSTLIJST_ID                    INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  CONSTRAINT PK_POSTLIJSTEN PRIMARY KEY (POSTLIJST_ID)
);

CREATE TABLE SEDES.REGIOS (
  LAND_ID                         INTEGER         NOT NULL,
  NAAM                            VARCHAR(100)    NOT NULL,
  REGIOKODE                       VARCHAR(5)      NOT NULL,
  REGIO_ID                        INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  CONSTRAINT PK_REGIOS PRIMARY KEY (REGIO_ID)
);

CREATE TABLE SEDES.WERELDDEELNAMEN (
  NAAM                            VARCHAR(100)    NOT NULL,
  TAAL                            CHAR(2)         NOT NULL,
  WERELDDEEL_ID                   INTEGER         NOT NULL,
  CONSTRAINT PK_WERELDDEELNAMEN PRIMARY KEY (WERELDDEEL_ID, TAAL)
);

CREATE TABLE SEDES.WERELDDELEN (
  WERELDDEEL_ID                   INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  CONSTRAINT PK_WERELDDELEN PRIMARY KEY (WERELDDEEL_ID)
);

-- Views

-- Constraints
ALTER TABLE SEDES.KONTAKTADRESSEN
  ADD CONSTRAINT FK_KAD_ADRES_ID FOREIGN KEY (ADRES_ID)
  REFERENCES SEDES.ADRESSEN (ADRES_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.KONTAKTADRESSEN
  ADD CONSTRAINT FK_KAD_KONTAKT_ID FOREIGN KEY (KONTAKT_ID)
  REFERENCES SEDES.KONTAKTEN (KONTAKT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.KONTAKTADRESSEN
  ADD CONSTRAINT CHK_KAD_TAAL  CHECK (TAAL = LOWER(TAAL));

ALTER TABLE SEDES.KONTAKTADRESSEN
  ADD CONSTRAINT UK_KAT_PER_KONTAKTADRESTYPE UNIQUE (KONTAKTADRESTYPE, ADRES_ID, KONTAKT_ID, STARTDATUM);

ALTER TABLE SEDES.KONTAKTEN
  ADD CONSTRAINT CHK_KON_KONTAKTTYPE CHECK(KONTAKTTYPE = ANY (ARRAY['G', 'P', 'R']));

ALTER TABLE SEDES.KONTAKTEN
  ADD CONSTRAINT CHK_KON_TAAL  CHECK (TAAL = LOWER(TAAL));

ALTER TABLE SEDES.KONTAKTKONTAKTEN
  ADD CONSTRAINT FK_KKO_CHILDKONTAKT FOREIGN KEY (CHILDKONTAKT)
  REFERENCES SEDES.KONTAKTEN (KONTAKT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.KONTAKTKONTAKTEN
  ADD CONSTRAINT FK_KKO_PARENTKONTAKT FOREIGN KEY (PARENTKONTAKT)
  REFERENCES SEDES.KONTAKTEN (KONTAKT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.KONTAKTKONTAKTEN
  ADD CONSTRAINT UK_KKO_KONTAKTKONTAKT UNIQUE (PARENTKONTAKT, CHILDKONTAKT, STARTDATUM);

ALTER TABLE SEDES.LANDEN
  ADD CONSTRAINT FK_LND_MUNT_ID FOREIGN KEY (MUNT_ID)
  REFERENCES SEDES.MUNTEN (MUNT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.LANDEN
  ADD CONSTRAINT FK_LND_WERELDDEEL_ID FOREIGN KEY (WERELDDEEL_ID)
  REFERENCES SEDES.WERELDDELEN (WERELDDEEL_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.LANDNAMEN
  ADD CONSTRAINT CHK_LNM_TAAL  CHECK (TAAL = LOWER(TAAL));

ALTER TABLE SEDES.LANDNAMEN
  ADD CONSTRAINT FK_LNM_LAND_ID FOREIGN KEY (LAND_ID)
  REFERENCES SEDES.LANDEN (LAND_ID)
  ON DELETE CASCADE
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.PLAATSEN
  ADD CONSTRAINT FK_PLA_LAND_ID FOREIGN KEY (LAND_ID)
  REFERENCES SEDES.LANDEN (LAND_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.PLAATSEN
  ADD CONSTRAINT FK_PLA_REGIO_ID FOREIGN KEY (REGIO_ID)
  REFERENCES SEDES.REGIOS (REGIO_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.POSTLIJST_KONTAKTEN
  ADD CONSTRAINT FK_PLK_KONTAKT_ID FOREIGN KEY (KONTAKT_ID)
  REFERENCES SEDES.KONTAKTEN (KONTAKT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.POSTLIJST_KONTAKTEN
  ADD CONSTRAINT FK_PLK_POSTLIJST_ID FOREIGN KEY (POSTLIJST_ID)
  REFERENCES SEDES.POSTLIJSTEN (POSTLIJST_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.REGIOS
  ADD CONSTRAINT FK_REG_LAND_ID FOREIGN KEY (LAND_ID)
  REFERENCES SEDES.LANDEN (LAND_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.WERELDDEELNAMEN
  ADD CONSTRAINT CHK_WDM_TAAL  CHECK (TAAL = LOWER(TAAL));

ALTER TABLE SEDES.WERELDDEELNAMEN
  ADD CONSTRAINT FK_WDN_WERELDDEEL_ID FOREIGN KEY (WERELDDEEL_ID)
  REFERENCES SEDES.WERELDDELEN (WERELDDEEL_ID)
  ON DELETE CASCADE
  ON UPDATE RESTRICT;

-- Grant rechten
GRANT SELECT                         ON TABLE SEDES.ADRESSEN                TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.KONTAKTADRESSEN         TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.KONTAKTEN               TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.KONTAKTKONTAKTEN        TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.LANDEN                  TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.LANDNAMEN               TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.MUNTEN                  TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.PLAATSEN                TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.POSTLIJST_KONTAKTEN     TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.POSTLIJSTEN             TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.REGIOS                  TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.WERELDDEELNAMEN         TO SEDES_SEL;
GRANT SELECT                         ON TABLE SEDES.WERELDDELEN             TO SEDES_SEL;

GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.ADRESSEN                TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.KONTAKTADRESSEN         TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.KONTAKTEN               TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.KONTAKTKONTAKTEN        TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.LANDEN                  TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.LANDNAMEN               TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.MUNTEN                  TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.PLAATSEN                TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.POSTLIJST_KONTAKTEN     TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.POSTLIJSTEN             TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.REGIOS                  TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.WERELDDEELNAMEN         TO SEDES_UPD;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.WERELDDELEN             TO SEDES_UPD;

-- Commentaren
COMMENT ON TABLE  SEDES.ADRESSEN                          IS 'Deze tabel bevat alle adressenen. Dit kunnen fysieke adressen zijn maar ook telefoonnummers en e-mail adressen.';
COMMENT ON COLUMN SEDES.ADRESSEN.ADRES_ID                 IS 'De sleutel van het adres.';
COMMENT ON COLUMN SEDES.ADRESSEN.ADRESDATA                IS 'Het adres.';
COMMENT ON COLUMN SEDES.ADRESSEN.OPMERKING                IS 'Een opmerking voor dit adres.';
COMMENT ON COLUMN SEDES.ADRESSEN.PLAATS_ID                IS 'Voor een fysiek adres is dit de sleutel van de plaats.';
COMMENT ON COLUMN SEDES.ADRESSEN.SUB_POSTKODE             IS 'Extra code bij de postkode.';
COMMENT ON TABLE  SEDES.KONTAKTADRESSEN                   IS 'Deze tabel bevat de adressen van de kontakten.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.ADRES_ID          IS 'De sleutel van het adres.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.EINDDATUM         IS 'De datum waarna dit kontaktadres niet meer geldig is.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.KONTAKTADRES_ID   IS 'De sleutel van het kontaktadres.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.KONTAKTADRESTYPE  IS 'Het type van het kontaktadres.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.KONTAKT_ID        IS 'De sleutel van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.OPMERKING         IS 'Een opmerking voor dit kontaktadres.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.STARTDATUM        IS 'De datum waarop dit kontaktadres is ontstaan.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.SUB_ADRES         IS 'Extra adres informatie.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.TAAL              IS 'De taal, ISO 639-2T, die dit kontaktadres gebruikt.';
COMMENT ON TABLE  SEDES.KONTAKTEN                         IS 'Deze tabel bevat alle kontakten. Dit zijn  personen, groepen of bedrijven. De betekenis van de velden kan veranderen per KONTAKTTYPE.';
COMMENT ON COLUMN SEDES.KONTAKTEN.AANSPREEK_ID            IS 'De code voor de aanspreektitel.';
COMMENT ON COLUMN SEDES.KONTAKTEN.GEBOORTEDATUM           IS 'De geboortedatum (of oprichtingsdatum) van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.GEBRUIKERSNAAM          IS 'De gebruikersnaam van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.INITIALEN               IS 'De initialen van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.KONTAKT_ID              IS 'De sleutel van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.KONTAKTTYPE             IS 'Het type kontakt. Groep, Persoon of Rechtspersoon.';
COMMENT ON COLUMN SEDES.KONTAKTEN.NAAM                    IS 'De naam van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.OPMERKING               IS 'Een opmerking voor dit kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.PSEUDONIEM              IS 'De pseudoniem van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.ROEPNAAM                IS 'De roepnaam van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.TAAL                    IS 'De taal, ISO 639-2T, die dit kontakt gebruikt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.TUSSENVOEGSEL           IS 'Eerste deel van achternaam die buiten de sortering valt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.VOORNAAM                IS 'De voornaam van dit kontakt.';
COMMENT ON TABLE  SEDES.MUNTEN                            IS 'Deze tabel bevat alle munten (valuta''s).';
COMMENT ON COLUMN SEDES.MUNTEN.BESTAAT                    IS 'Bestaat de munt nog (J/N)?';
COMMENT ON COLUMN SEDES.MUNTEN.DECIMALEN                  IS 'Aantal decimalen voor de subeenheid.';
COMMENT ON COLUMN SEDES.MUNTEN.ISO3                       IS 'De ISO3 code van de munt.';
COMMENT ON COLUMN SEDES.MUNTEN.MUNT_ID                    IS 'De sleutel van de munt.';
COMMENT ON COLUMN SEDES.MUNTEN.MUNTTEKEN                  IS 'Het teken van de munt.';
COMMENT ON COLUMN SEDES.MUNTEN.NAAM                       IS 'De naam van de munt.';
COMMENT ON COLUMN SEDES.MUNTEN.SUBEENHEID                 IS 'De naam van de subeenheid van de munt.';

-- Default waardes
INSERT INTO SEDES.WERELDDELEN VALUES (0);

INSERT INTO SEDES.WERELDDEELNAMEN VALUES ('Aarde', 'nl', 0);

INSERT INTO SEDES.MUNTEN VALUES ('N', 2, 'Onbekend', 0, '-', NULL, NULL);

INSERT INTO SEDES.LANDEN VALUES ('N', NULL, '-', 0, NULL, 0, NULL, '1', '-', '??', NULL, 0);

INSERT INTO SEDES.LANDNAMEN VALUES (NULL, 0, 'Onbekend', NULL, 'nl');

INSERT INTO DOOS.I18N_LIJSTEN
        (CODE, OMSCHRIJVING)
 VALUES ('sedes.kontakt.type', 'Lijst met de kontakttypes.');

INSERT INTO DOOS.I18N_LIJSTEN
        (CODE, OMSCHRIJVING)
 VALUES ('sedes.kontaktadres.type', 'Lijst met de kontaktadrestypes.');

INSERT INTO DOOS.I18N_LIJSTEN
        (CODE, OMSCHRIJVING)
 VALUES ('sedes.aanspreektitel', 'Lijst met aanspreektitels.');
