ALTER TABLE SEDES.ADRESSEN ALTER COLUMN OPMERKING TYPE VARCHAR(2000);
ALTER TABLE SEDES.LANDEN ALTER COLUMN BESTAAT TYPE CHAR(1);
ALTER TABLE SEDES.LANDNAMEN RENAME COLUMN LANDNAAM TO NAAM;
ALTER TABLE SEDES.MUNTEN ALTER COLUMN BESTAAT TYPE CHAR(1);
ALTER TABLE SEDES.MUNTEN RENAME COLUMN MUNT TO NAAM;
ALTER TABLE SEDES.REGIOS RENAME COLUMN REGIO TO NAAM;
ALTER TABLE SEDES.WERELDDEELNAMEN RENAME COLUMN WERELDDEELNAAM TO NAAM;

ALTER TABLE SEDES.ADRESSEN ALTER COLUMN ADRES_ID DROP DEFAULT;
ALTER TABLE SEDES.ADRESSEN ALTER COLUMN ADRES_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.adressen', 'adres_id'), COALESCE(MAX(ADRES_ID), 1))
FROM SEDES.ADRESSEN;
DROP SEQUENCE SEDES.SEQ_ADRESSEN;
ALTER TABLE SEDES.ADRESSEN RENAME COLUMN ADRES TO ADRESDATA;

ALTER TABLE SEDES.KONTAKTADRESSEN ALTER COLUMN KONTAKTADRES_ID DROP DEFAULT;
ALTER TABLE SEDES.KONTAKTADRESSEN ALTER COLUMN KONTAKTADRES_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.kontaktadressen', 'kontaktadres_id'), COALESCE(MAX(KONTAKTADRES_ID), 1))
FROM SEDES.KONTAKTADRESSEN;
DROP SEQUENCE SEDES.SEQ_KONTAKTADRESSEN;

ALTER TABLE IF EXISTS SEDES.KONTAKTEN ALTER COLUMN KONTAKT_ID DROP DEFAULT;
ALTER TABLE IF EXISTS SEDES.KONTAKTEN ALTER COLUMN KONTAKT_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.kontakten', 'kontakt_id'), COALESCE(MAX(KONTAKT_ID), 1))
FROM SEDES.KONTAKTEN;
DROP SEQUENCE SEDES.SEQ_KONTAKTEN;
ALTER TABLE IF EXISTS SEDES.KONTAKTEN ALTER COLUMN TAAL SET NOT NULL;

ALTER TABLE SEDES.KONTAKTEN
  ADD COLUMN KONTAKTTYPE    CHAR(1)         NOT NULL  DEFAULT 'P',
  DROP COLUMN OFFICIEEL,
  ALTER OPMERKING TYPE      VARCHAR(2000),
  ADD COLUMN  PSEUDONIEM    VARCHAR(255),
  ADD COLUMN  ROEPNAAM      VARCHAR(255),
  DROP COLUMN SEXE,
  ALTER TAAL      TYPE      CHAR(3),
  ADD COLUMN TUSSENVOEGSEL  VARCHAR(10);

ALTER TABLE SEDES.KONTAKTADRESSEN
  ALTER COLUMN KONTAKTADRESTYPE TYPE VARCHAR(10),
  ADD COLUMN EINDDATUM DATE,
  DROP COLUMN KONTAKTTYPE,
  ALTER COLUMN OPMERKING TYPE VARCHAR(2000),
  ADD COLUMN STARTDATUM DATE NOT NULL,
  ALTER COLUMN TAAL TYPE CHAR(3);

ALTER TABLE SEDES.LANDEN ALTER COLUMN LAND_ID DROP DEFAULT;
ALTER TABLE SEDES.LANDEN ALTER COLUMN LAND_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.landen', 'land_id'), COALESCE(MAX(LAND_ID), 1))
FROM SEDES.LANDEN;
DROP SEQUENCE SEDES.SEQ_LANDEN;

ALTER TABLE SEDES.MUNTEN ALTER COLUMN MUNT_ID DROP DEFAULT;
ALTER TABLE SEDES.MUNTEN ALTER COLUMN MUNT_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.munten', 'munt_id'), COALESCE(MAX(MUNT_ID), 1))
FROM SEDES.MUNTEN;
DROP SEQUENCE SEDES.SEQ_MUNTEN;

ALTER TABLE SEDES.PLAATSEN ALTER COLUMN PLAATS_ID DROP DEFAULT;
ALTER TABLE SEDES.PLAATSEN ALTER COLUMN PLAATS_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.plaatsen', 'plaats_id'), COALESCE(MAX(PLAATS_ID), 1))
FROM SEDES.PLAATSEN;
DROP SEQUENCE SEDES.SEQ_PLAATSEN;

ALTER TABLE SEDES.POSTLIJSTEN ALTER COLUMN POSTLIJST_ID DROP DEFAULT;
ALTER TABLE SEDES.POSTLIJSTEN ALTER COLUMN POSTLIJST_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.postlijsten', 'postlijst_id'), COALESCE(MAX(POSTLIJST_ID), 1))
FROM SEDES.POSTLIJSTEN;
DROP SEQUENCE SEDES.SEQ_POSTLIJSTEN;

ALTER TABLE SEDES.REGIOS ALTER COLUMN REGIO_ID DROP DEFAULT;
ALTER TABLE SEDES.REGIOS ALTER COLUMN REGIO_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.regios', 'regio_id'), COALESCE(MAX(REGIO_ID), 1))
FROM SEDES.REGIOS;
DROP SEQUENCE SEDES.SEQ_REGIOS;

ALTER TABLE SEDES.WERELDDELEN ALTER COLUMN WERELDDEEL_ID DROP DEFAULT;
ALTER TABLE SEDES.WERELDDELEN ALTER COLUMN WERELDDEEL_ID ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('sedes.werelddelen', 'werelddeel_id'), COALESCE(MAX(WERELDDEEL_ID), 1))
FROM SEDES.WERELDDELEN;
DROP SEQUENCE SEDES.SEQ_WERELDDELEN;

ALTER TABLE SEDES.KONTAKTADRESSEN
  DROP CONSTRAINT FK_KAD_ADRES_ID;

ALTER TABLE SEDES.KONTAKTADRESSEN
  ADD CONSTRAINT FK_KAD_ADRES_ID FOREIGN KEY (ADRES_ID)
  REFERENCES SEDES.ADRESSEN (ADRES_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.KONTAKTADRESSEN
  DROP CONSTRAINT FK_KAD_KONTAKT_ID;

ALTER TABLE SEDES.KONTAKTADRESSEN
  ADD CONSTRAINT FK_KAD_KONTAKT_ID FOREIGN KEY (KONTAKT_ID)
  REFERENCES SEDES.KONTAKTEN (KONTAKT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.KONTAKTADRESSEN
  ADD CONSTRAINT CHK_KAD_TAAL  CHECK (TAAL = LOWER(TAAL));

ALTER TABLE SEDES.KONTAKTADRESSEN
  ADD CONSTRAINT UK_KAT_PER_KONTAKTADRESTYPE UNIQUE (KONTAKTADRESTYPE, ADRES_ID, KONTAKT_ID, STARTDATUM);

ALTER TABLE SEDES.KONTAKTEN DROP CONSTRAINT CHK_GEB_KONTAKTTYPE;

ALTER TABLE SEDES.KONTAKTEN
  ADD CONSTRAINT CHK_KON_KONTAKTTYPE CHECK(KONTAKTTYPE = ANY (ARRAY['G', 'P', 'R']));

ALTER TABLE SEDES.KONTAKTEN
  ADD CONSTRAINT CHK_KON_TAAL  CHECK (TAAL = LOWER(TAAL));

ALTER TABLE SEDES.LANDEN
  DROP CONSTRAINT FK_LND_MUNT_ID;

ALTER TABLE SEDES.LANDEN
  ADD CONSTRAINT FK_LND_MUNT_ID FOREIGN KEY (MUNT_ID)
  REFERENCES SEDES.MUNTEN (MUNT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.LANDEN
  DROP CONSTRAINT FK_LND_WERELDDEEL_ID;

ALTER TABLE SEDES.LANDEN
  ADD CONSTRAINT FK_LND_WERELDDEEL_ID FOREIGN KEY (WERELDDEEL_ID)
  REFERENCES SEDES.WERELDDELEN (WERELDDEEL_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.PLAATSEN
  DROP CONSTRAINT FK_PLA_LAND_ID;

ALTER TABLE SEDES.PLAATSEN
  ADD CONSTRAINT FK_PLA_LAND_ID FOREIGN KEY (LAND_ID)
  REFERENCES SEDES.LANDEN (LAND_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.PLAATSEN
  DROP CONSTRAINT FK_PLA_REGIO_ID;

ALTER TABLE SEDES.PLAATSEN
  ADD CONSTRAINT FK_PLA_REGIO_ID FOREIGN KEY (REGIO_ID)
  REFERENCES SEDES.REGIOS (REGIO_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.POSTLIJST_KONTAKTEN
  DROP CONSTRAINT FK_PLK_KONTAKT_ID;

ALTER TABLE SEDES.POSTLIJST_KONTAKTEN
  ADD CONSTRAINT FK_PLK_KONTAKT_ID FOREIGN KEY (KONTAKT_ID)
  REFERENCES SEDES.KONTAKTEN (KONTAKT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.POSTLIJST_KONTAKTEN
  DROP CONSTRAINT FK_PLK_POSTLIJST_ID;

ALTER TABLE SEDES.POSTLIJST_KONTAKTEN
  ADD CONSTRAINT FK_PLK_POSTLIJST_ID FOREIGN KEY (POSTLIJST_ID)
  REFERENCES SEDES.POSTLIJSTEN (POSTLIJST_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.REGIOS
  DROP CONSTRAINT FK_REG_LAND_ID;

ALTER TABLE SEDES.REGIOS
  ADD CONSTRAINT FK_REG_LAND_ID FOREIGN KEY (LAND_ID)
  REFERENCES SEDES.LANDEN (LAND_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.LANDNAMEN
  ADD CONSTRAINT CHK_LNM_TAAL  CHECK (TAAL = LOWER(TAAL));

ALTER TABLE SEDES.WERELDDEELNAMEN
  ADD CONSTRAINT CHK_WDM_TAAL  CHECK (TAAL = LOWER(TAAL));

CREATE TABLE SEDES.KONTAKTKONTAKTEN (
  CHILDKONTAKT                    INTEGER         NOT NULL,
  EINDDATUM                       DATE,
  KONTAKTKONTAKT_ID               INTEGER         NOT NULL  GENERATED ALWAYS AS IDENTITY,
  PARENTKONTAKT                   INTEGER         NOT NULL,
  STARTDATUM                      DATE            NOT NULL,
  CONSTRAINT PK_KONTAKTKONTAKTEN PRIMARY KEY (KONTAKTKONTAKT_ID)
);

ALTER TABLE SEDES.KONTAKTEN
  ADD CONSTRAINT CHK_GEB_KONTAKTTYPE CHECK(KONTAKTTYPE = ANY (ARRAY['G', 'P', 'R']));

ALTER TABLE SEDES.KONTAKTKONTAKTEN
  ADD CONSTRAINT FK_KKO_CHILDKONTAKT FOREIGN KEY (CHILDKONTAKT)
  REFERENCES SEDES.KONTAKTEN (KONTAKT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.KONTAKTKONTAKTEN
  ADD CONSTRAINT FK_KKO_PARENTKONTAKT FOREIGN KEY (PARENTKONTAKT)
  REFERENCES SEDES.KONTAKTEN (KONTAKT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE SEDES.KONTAKTKONTAKTEN
  ADD CONSTRAINT UK_KKO_KONTAKTKONTAKT UNIQUE (PARENTKONTAKT, CHILDKONTAKT, STARTDATUM);

GRANT SELECT                         ON TABLE SEDES.KONTAKTKONTAKTEN        TO SEDES_SEL;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE SEDES.KONTAKTKONTAKTEN        TO SEDES_UPD;

COMMENT ON TABLE  SEDES.ADRESSEN                        IS 'Deze tabel bevat alle adressenen. Dit kunnen fysieke adressen zijn maar ook telefoonnummers en e-mail adressen.';
COMMENT ON COLUMN SEDES.ADRESSEN.ADRES_ID               IS 'De sleutel van het adres.';
COMMENT ON COLUMN SEDES.ADRESSEN.ADRESDATA              IS 'Het adres.';
COMMENT ON COLUMN SEDES.ADRESSEN.OPMERKING              IS 'Een opmerking voor dit adres.';
COMMENT ON COLUMN SEDES.ADRESSEN.PLAATS_ID              IS 'Voor een fysiek adres is dit de sleutel van de plaats.';
COMMENT ON COLUMN SEDES.ADRESSEN.SUB_POSTKODE           IS 'Extra code bij de postkode.';
COMMENT ON TABLE  SEDES.KONTAKTADRESSEN                 IS 'Deze tabel bevat de adressen van de kontakten.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.ADRES_ID        IS 'De sleutel van het adres.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.ADRESTYPE       IS 'Het type van het adres.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.EINDDATUM       IS 'De datum waarna dit kontaktadres niet meer geldig is.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.KONTAKTADRES_ID IS 'De sleutel van het kontaktadres.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.KONTAKT_ID      IS 'De sleutel van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.OPMERKING       IS 'Een opmerking voor dit kontaktadres.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.STARTDATUM      IS 'De datum waarop dit kontaktadres is ontstaan.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.SUB_ADRES       IS 'Extra adres informatie.';
COMMENT ON COLUMN SEDES.KONTAKTADRESSEN.TAAL            IS 'De taal, ISO 639-2T, die dit kontaktadres gebruikt.';
COMMENT ON TABLE  SEDES.KONTAKTEN                       IS 'Deze tabel bevat alle kontakten. Dit zijn  personen, groepen of bedrijven. De betekenis van de velden kan veranderen per KONTAKTTYPE.';
COMMENT ON COLUMN SEDES.KONTAKTEN.AANSPREEK_ID          IS 'De code voor de aanspreektitel.';
COMMENT ON COLUMN SEDES.KONTAKTEN.GEBOORTEDATUM         IS 'De geboortedatum (of oprichtingsdatum) van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.GEBRUIKERSNAAM        IS 'De gebruikersnaam van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.INITIALEN             IS 'De initialen van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.KONTAKT_ID            IS 'De sleutel van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.KONTAKTTYPE           IS 'Het type kontakt. Groep, Persoon of Rechtspersoon.';
COMMENT ON COLUMN SEDES.KONTAKTEN.NAAM                  IS 'De naam van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.OPMERKING             IS 'Een opmerking voor dit kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.PSEUDONIEM            IS 'De pseudoniem van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.ROEPNAAM              IS 'De roepnaam van het kontakt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.TAAL                  IS 'De taal, ISO 639-2T, die dit kontakt gebruikt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.TUSSENVOEGSEL         IS 'Eerste deel van achternaam die buiten de sortering valt.';
COMMENT ON COLUMN SEDES.KONTAKTEN.VOORNAAM              IS 'De voornaam van dit kontakt.';
COMMENT ON TABLE  SEDES.MUNTEN                          IS 'Deze tabel bevat alle munten (valuta''s).';
COMMENT ON COLUMN SEDES.MUNTEN.BESTAAT                  IS 'Bestaat de munt nog (J/N)?';
COMMENT ON COLUMN SEDES.MUNTEN.DECIMALEN                IS 'Aantal decimalen voor de subeenheid.';
COMMENT ON COLUMN SEDES.MUNTEN.ISO3                     IS 'De ISO3 code van de munt.';
COMMENT ON COLUMN SEDES.MUNTEN.MUNT_ID                  IS 'De sleutel van de munt.';
COMMENT ON COLUMN SEDES.MUNTEN.MUNTTEKEN                IS 'Het teken van de munt.';
COMMENT ON COLUMN SEDES.MUNTEN.NAAM                     IS 'De naam van de munt.';
COMMENT ON COLUMN SEDES.MUNTEN.SUBEENHEID               IS 'De naam van de subeenheid van de munt.';

INSERT INTO DOOS.I18N_LIJSTEN
        (CODE, OMSCHRIJVING)
 VALUES ('sedes.kontakt.type', 'Lijst met de kontakttypes.');

INSERT INTO DOOS.I18N_LIJSTEN
        (CODE, OMSCHRIJVING)
 VALUES ('sedes.kontaktadres.type', 'Lijst met de kontaktadrestypes.');

INSERT INTO DOOS.I18N_LIJSTEN
        (CODE, OMSCHRIJVING)
 VALUES ('sedes.aanspreektitel', 'Lijst met aanspreektitels.');

COMMIT;
